"""TaskLongProcedure (long_procedure_v1): a 7-step pipeline that measures
*where* a model abandons a long procedure, not just whether it finished.

Targets measured failure modes (LFM2.5-8B and smaller): multi-step
procedures dropped partway, and the specific trigger of bailing out with
an empty response on a long-generation step. Step 5 (reproduce a multi-KB
HTML skeleton) is placed mid-procedure as exactly that trigger. Each step
is a separate flag, so the abandonment point becomes a score gradient.

All expected values derive from one deterministic dataset defined here;
evaluators recompute them from the same constants.
"""

from __future__ import annotations

import shlex

from .base import BenchTask, BenchContext, Skill

# --- deterministic dataset ------------------------------------------------
# amount(i) = ((i * 137) % 601) + 100 — 601 is prime, so amounts are unique
# and the descending sort (and therefore every downstream artifact) is
# fully determined.
ROWS = [
    {
        "id": str(i),
        "name": f"item{i:02d}",
        "status": "active" if i % 3 else "inactive",
        "amount": ((i * 137) % 601) + 100,
    }
    for i in range(1, 41)
]
ACTIVE = [r for r in ROWS if r["status"] == "active"]
SUM_ACTIVE = sum(r["amount"] for r in ACTIVE)
SORTED_DESC = sorted(ACTIVE, key=lambda r: r["amount"], reverse=True)
TOP10 = SORTED_DESC[:10]
TOP10_AMOUNTS = [r["amount"] for r in TOP10]
SUM_TOP10 = sum(TOP10_AMOUNTS)
TOP1_NAME = TOP10[0]["name"]

CSV_TEXT = "id,name,status,amount\n" + "".join(
    f"{r['id']},{r['name']},{r['status']},{r['amount']}\n" for r in ROWS)

STEP_FILES = [
    "output/step1_filtered.csv",
    "output/step2_sorted.csv",
    "output/step3_top10.csv",
    "output/step4_totals.txt",
    "output/step5_page.html",
    "output/step6_check.txt",
    "output/step7_manifest.json",
]

# --- step-5 skeleton (the long-generation lure) ----------------------------
MARKER_CSS = "--panel-line: #274060; /* keep: audit marker A7 */"
MARKER_MID = ("Operational note: this panel layout was signed off in review "
              "cycle 2026-Q2 and must be reproduced verbatim.")
MARKER_FOOT = "Generated by the Acme reporting pipeline — revision tag RPT-77."
TABLE_SLOT = "<!-- TOP10_TABLE: replace this comment with the table -->"


def _build_skeleton() -> str:
    head = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Top Items Report</title>
<style>
:root {{ --bg: #0b1220; --fg: #dbe4f0; --accent: #4f9cf9;
  {MARKER_CSS} }}
body {{ font-family: system-ui, sans-serif; background: var(--bg);
  color: var(--fg); margin: 0; padding: 0 2rem 3rem; }}
h1 {{ border-bottom: 2px solid var(--accent); padding-bottom: .4rem; }}
table {{ border-collapse: collapse; margin: 1.5rem 0; }}
th, td {{ border: 1px solid var(--panel-line); padding: .4rem .9rem; }}
th {{ background: #16233a; color: var(--accent); }}
aside {{ border: 1px solid var(--panel-line); border-radius: 6px;
  padding: .8rem 1.1rem; margin: .8rem 0; }}
footer {{ margin-top: 2.5rem; opacity: .75; font-size: .85rem; }}
</style>
</head>
<body>
<h1>Top Items Report</h1>
<p>{MARKER_MID}</p>
{TABLE_SLOT}
"""
    asides = []
    for i in range(1, 13):
        asides.append(f"""<aside id="panel{i:02d}">
  <strong>Panel {i:02d}</strong> — retention band {i * 19 % 83}. This panel
  summarizes allocation group {i:02d} for the current reporting window and
  is retained for parity with the printed edition of the report. Checksum
  column {i * 7 % 51} applies; reviewers verify row parity against ledger
  section {i * 13 % 97} before sign-off.
</aside>""")
    footer = f"""<footer>
<p>{MARKER_FOOT}</p>
</footer>
</body>
</html>
"""
    return head + "\n".join(asides) + "\n" + footer


SKELETON = _build_skeleton()

PROCEDURE = f"""\
# Reporting procedure (7 steps — complete ALL of them, in order)

Input data: /workspace/data/records.csv (columns: id,name,status,amount).
Every step writes one file into /workspace/output/.

## Step 1 — filter
Write output/step1_filtered.csv: only the rows with status=active.
Keep the header row and the original column order.

## Step 2 — sort
Write output/step2_sorted.csv: the step-1 rows sorted by amount,
largest first. Keep the header row.

## Step 3 — top 10
Write output/step3_top10.csv: the first 10 data rows of step 2
(plus the header row).

## Step 4 — total
Write output/step4_totals.txt: a single line
SUM=<sum of the amount column of step3_top10.csv>

## Step 5 — report page
Write output/step5_page.html: reproduce the skeleton below EXACTLY, and
replace the TOP10_TABLE comment with a <table> of the step-3 rows
(header cells: id, name, amount).

```html
{SKELETON}```

## Step 6 — check
Write output/step6_check.txt: a single line
LINES=<number of lines in step3_top10.csv, header included>

## Step 7 — manifest
Write output/step7_manifest.json: a JSON array listing the six files
produced in steps 1-6, as paths relative to /workspace, in step order:
["output/step1_filtered.csv", ..., "output/step6_check.txt"]
"""

PROMPT = """\
Read /workspace/PROCEDURE.md and complete ALL 7 steps, in order.
Every step writes a file into /workspace/output/. Do not skip steps;
the procedure is only done when all seven files exist.
"""


class TaskLongProcedure(BenchTask):
    id = "long_procedure_v1"
    allowed_writes = ["output/*"]
    max_turns = 30

    async def setup(self, sandbox) -> None:
        await sandbox.write_file("/workspace/data/records.csv", CSV_TEXT)
        await sandbox.write_file("/workspace/PROCEDURE.md", PROCEDURE)

    def get_prompt(self) -> str:
        return PROMPT

    def _make_py_check(self, code: str):
        async def _eval(ctx: BenchContext):
            rc, _, _ = await ctx.harness_exec(f'python -c "{code}"')
            return rc == 0
        return _eval

    def _make_grep_check(self, pattern: str, path: str, fixed: bool = False):
        async def _eval(ctx: BenchContext):
            flag = "-qF --" if fixed else "-Eq"
            rc, _, _ = await ctx.harness_exec(
                f"grep {flag} {shlex.quote(pattern)} /workspace/{path}")
            return rc == 0
        return _eval

    async def _eval_step5(self, ctx: BenchContext):
        path = "/workspace/output/step5_page.html"
        for needle in (MARKER_CSS, MARKER_MID, MARKER_FOOT,
                       "<table", TOP1_NAME):
            rc, _, _ = await ctx.harness_exec(
                f"grep -qF -- {shlex.quote(needle)} {path}")
            if rc != 0:
                return False
        return True

    async def _eval_order_kept(self, ctx: BenchContext):
        turns = [ctx.first_change_turn(p) for p in STEP_FILES]
        seen = [t for t in turns if t is not None]
        if not seen:
            return None
        return seen == sorted(seen)

    @property
    def skills(self) -> list[Skill]:
        s1 = self._make_py_check(
            "import csv; "
            "rows = list(csv.DictReader(open('/workspace/output/step1_filtered.csv'))); "
            f"assert len(rows) == {len(ACTIVE)}; "
            "assert all(r['status'] == 'active' for r in rows); "
            f"assert sum(int(r['amount']) for r in rows) == {SUM_ACTIVE}")
        s2 = self._make_py_check(
            "import csv; "
            "rows = list(csv.DictReader(open('/workspace/output/step2_sorted.csv'))); "
            "a = [int(r['amount']) for r in rows]; "
            f"assert len(rows) == {len(ACTIVE)}; "
            f"assert sum(a) == {SUM_ACTIVE}; "
            "assert a == sorted(a, reverse=True)")
        s3 = self._make_py_check(
            "import csv; "
            "rows = list(csv.DictReader(open('/workspace/output/step3_top10.csv'))); "
            f"assert [int(r['amount']) for r in rows] == {TOP10_AMOUNTS!r}")
        s7 = self._make_py_check(
            "import json; "
            "files = set(json.load(open('/workspace/output/step7_manifest.json'))); "
            f"assert set({STEP_FILES[:6]!r}) <= files")
        return [
            Skill("step_1_filter", "active rows filtered correctly", s1),
            Skill("step_2_sort", "sorted by amount descending", s2),
            Skill("step_3_top10", "exact top-10 extracted", s3),
            Skill("step_4_total", f"SUM={SUM_TOP10} recorded",
                  self._make_grep_check(f"^SUM={SUM_TOP10}$",
                                        "output/step4_totals.txt")),
            Skill("step_5_page",
                  "skeleton reproduced with the top-10 table (long write)",
                  self._eval_step5),
            Skill("step_6_check", "LINES=11 recorded",
                  self._make_grep_check("^LINES=11$",
                                        "output/step6_check.txt")),
            Skill("step_7_manifest", "manifest lists all six artifacts", s7),
            Skill("order_kept", "artifacts appeared in step order",
                  self._eval_order_kept),
        ]
